config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  root 'pages#home'
  get 'yomanga' => 'pages#yomanga'
  get 'search' => 'mangas#search'
  post 'search' => 'mangas#search'
  get 'subcrible' => 'mangas#subcrible'
  resources :mangas do
    resources :chapters
  end
  resources :bookmarks
  resources :comments

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :manga, class_name: "Manga"
  validates :user_id, presence: true
  validates :manga_id, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :manga
  default_scope -> { order(chapter_index: :asc) }
  has_many :comments, :as => :commentable
  extend FriendlyId
  friendly_id :chapter_number, use: :slugged
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/manga.rb
class Manga < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  # paginates_per 30
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :comments, :as => :commentable
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookmarks, dependent: :destroy
  has_many :mangas, through: :bookmarks
  has_many :comments, :as => :commentable
  def follow(manga)
    bookmarks.create(manga_id: manga.id)
  end

  def unfollow(manga)
    bookmarks.find_by(manga_id: manga.id).destroy
  end

  def follow?(manga)
    mangas.include?(manga)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :titles
  after_filter :store_location
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def titles
    @titles = Manga.pluck(:title)
  end

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_update_path_for(resource)
    session[:previous_url] || root_path
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = current_user.bookmarks.new
  end

  def create
    @manga = Manga.find_by(id: params[:manga_id])
    current_user.follow(@manga)
    # redirect_to manga
    respond_to do |format|
      format.html { redirect_to @manga }
      format.js
    end
  end

  def destroy
    # Bookmark.find_by(id: params[:id]).destroy
    @manga = Manga.find_by(id: params[:manga_id])
    current_user.unfollow(@manga)
    # redirect_to manga
    respond_to do |format|
      format.html { redirect_to @manga }
      format.js
    end

  end

  def index
    @mangas = current_user.mangas
    render mangas_path
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def show
    @manga = Manga.friendly.find(params[:manga_id])
    @chapters = @manga.chapters
    @chapter = @chapters.friendly.find(params[:id])
    chapter_index = @chapter.chapter_index
    chapter_index_next = chapter_index - 1
    chapter_index_prev = chapter_index + 1
    @next_chap = @chapters.find_by(chapter_index: chapter_index_next)
    @prev_chap = @chapters.find_by(chapter_index: chapter_index_prev)
    @comments = @chapter.comments.reverse
    @commentable = @chapter
    @commentable_type = 'Chapter'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.create(commentable_id: params[:commentable_id], commentable_type: params[:commentable_type], content: params[:comment][:content], user_id: current_user.id)
    if @comment.save
      if params[:commentable_type] == 'Manga'
        @commentable = Manga.find_by(id: params[:commentable_id])
      else
        @commentable = Chapter.find_by(id: params[:commentable_id])
      end
      @comments = @commentable.comments.reverse
    else
      render :action => 'new'
    end
    # redirect_to session[:previous_url]
    respond_to do |format|
      format.html { redirect_to session[:previous_url] }
      format.js
    end
  end




end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  require 'will_paginate/array'
  def index
    # @mangas = Manga.all
    @mangas = Manga.paginate(page: params[:page])
    @top_mangas = Manga.all.where(top: true)
    @new_mangas = Manga.all.where(new: true)
    @genres = Manga.all.map(&:genres).join(",").split(",").uniq
  end

  def subcrible
    @mangas = current_user.mangas.paginate(:page => params[:page], :per_page => 20)
    @genres = Manga.all.map(&:genres).join(",").split(",").uniq
    render 'index'
  end

  def show
    @manga = Manga.friendly.find(params[:id])
    @chapters = @manga.chapters.all
    @comments = @manga.comments
    @commentable = @manga
    @commentable_type = 'Manga'
    @top_mangas = Manga.all.where(top: true)
    @new_mangas = Manga.all.where(new: true)
  end

  def search
    genres_yes = []
    genres_no = []
    @mangas = Manga.all
    @genres = Manga.all.map(&:genres).join(",").split(",").uniq
    @genres.each do |genre|
      g =genre.gsub(" ","_")
      if params[g] == "YES"
        genres_yes << genre
      elsif params[g] == "NO"
        genres_no << genre
      end
    end


    if params[:title]
      @mangas =[]
      Manga.all.each do |manga|
        puts manga.title
        @mangas << manga if manga.title[params[:title]]
      end
    end

    if params[:author]
      str =[]
      str << params[:author]
      @mangas = Manga.where.contains(authors: str)
    end

    if params[:genre] || genres_yes.any?
      genres_yes << params[:genre]
      genres_yes.compact!
      if genres_no.any?
        @mangas_no = Manga.where.contains(genres: genres_no)
        @mangas_yes = Manga.where.contains(genres: genres_yes)
        @mangas_excluded = Manga.all - @mangas_no
        @mangas = @mangas_yes & @mangas_excluded
      else
        @mangas = Manga.where.contains(genres: genres_yes)
      end
    end

    if (params['status'] == 'Completed') || (params['status'] == 'Ongoing')
      @mangas_status = Manga.where(status: params['status'])
      @mangas = @mangas_status & @mangas
    end

    @paginatable_mangas = @mangas
    @mangas = @paginatable_mangas.paginate(:page => params[:page], :per_page => 20)
    render 'index'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # HardWorker.perform_async('bob',5)

    # @feeds_mangas = Manga.all.sort_by(&:updated_at).reverse.take(12)
    @feeds_mangas = Manga.paginate(page: params[:page], per_page: 12).order('updated_at DESC')
    @top_mangas = Manga.all.where(top: true)
    @new_mangas = Manga.all.where(new: true)
    @cover_mangas = Manga.all.where(cover: true)
   respond_to do |format|
		  format.html
		  format.js
		end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/create.js.erb
$("#subcrible_form").html("<%= escape_javascript(render('layouts/unsubcrible')) %>");

app/views/bookmarks/destroy.js.erb
$('#subcrible_form').html("<%= escape_javascript(render('layouts/subcrible')) %>");

app/views/chapters/_navigation_bar.html.erb
<ul class='navigation-bar'>
  <li><%= link_to "#{@manga.title}", manga_path(@manga), class:'btn'%></li>
  <li>
   <div class='dropdown'>
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @chapter.chapter_number %><span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% @manga.chapters.each do |chap| %>
          <li><%= link_to "#{chap.chapter_number}", manga_chapter_path(@manga, chap) %></li>
        <% end %>
      </ul>
    </div>
  </li>
  <li class='pull-right'>
    <% if @prev_chap %>
      <%= link_to "Previous", manga_chapter_path(@manga, @prev_chap), class:'btn previous' %>
    <% else %>
      <%= link_to "Previous", '#', class:'btn previous disabled' %>
    <% end %>

    <% if @next_chap %>
      <%= link_to "Next", manga_chapter_path(@manga, @next_chap), class: 'btn next' %>
    <% else %>
      <%= link_to "Next", '#', class: 'btn next disabled' %>
    <% end %>
  </li>
</ul>

app/views/chapters/show.html.erb
<%= render 'navigation_bar' %>

<div class='picture-container'>
  <% @chapter.picture_urls.each do |pic| %>
    <%= image_tag pic %>
    <br>
  <% end %>
</div>

<%= render 'navigation_bar' %>

<div class='row'>
  <div class='col-lg-6 col-md-6 col-sm-6 col-lg-offset-3'>
    <%= render 'layouts/comment' %>
  </div>
</div>

app/views/comments/create.js.erb
$('#new_comment')[0].reset();
$("#comments").html("<%= escape_javascript(render('layouts/comment_display')) %>");

app/views/layouts/_comment.html.erb
<%= form_for(Comment.new, remote: true) do |f| %>
  <%= hidden_field_tag :commentable_id, @commentable.id %>
  <%= hidden_field_tag :commentable_type, @commentable_type %>
  <p>
    <%= f.text_area :content %>
    <%= f.submit "Submit", class:'btn' %>
  </p>
<% end %>

<div id="comments">
  <%= render '/layouts/comment_display' %>
</div>

app/views/layouts/_comment_display.html.erb
<% for comment in @comments %>
  <div class="comment">
    <% user = User.find_by(id: comment.user_id) %>
    <% gravatar_id = Digest::MD5::hexdigest(user.email.downcase) %>
    <% gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" %>
    <%= image_tag(gravatar_url, alt: user.email, class: "gravatar") %>
    <h3><%= user.email %></h3>
    <%=simple_format comment.content %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='footer'>

</div>

<style>
  .footer {
    color: red;
    height: 50px;
  }
</style>

app/views/layouts/_header.html.erb
<header>
  <div id='application-menu'>
    <%= link_to 'Hoang Manga', root_path, class:'navbar-brand' %>
    <%= link_to 'Manga Directory', mangas_path, class:'navbar-brand' %>

    <div id="the-basics">
      <%= form_for :manga, url: search_path, method: 'post' do %>
        <input class="typeahead" type="text" placeholder="Seach manga" name='title' >
        <input type = 'submit' value ='Submit' class='hidden'>
      <% end %>
    </div>

    <ul class='nav navbar-nav navbar-right'>

      <% if user_signed_in? %>
        <li>
          <a href=<%= subcrible_path %> >
            <span class='glyphicon glyphicon-bookmark'></span>
            Bookmark
          </a>
        </li>
        <li>
          <a href=<%= destroy_user_session_path %> data-method='delete'>
            <span class='glyphicon glyphicon-user'></span>
            Logout
          </a>
        </li>
      <% else %>
        <li>
          <a href='#' data-toggle='modal' data-target='#registermodal'>
            <span class='glyphicon glyphicon-plus-sign'></span>
            Register
          </a>
        </li>

        <li>
          <a href='#' data-toggle='modal' data-target='#loginmodal'>
            <span class='glyphicon glyphicon-user'></span>
            Login
          </a>
        </li>
      <% end %>


    </ul>

  </div>
</header>

<div id='registermodal' class='modal fade' role='dialog'>
  <div class='form-holder'>
    <h1>Register Form</h1>
    <%= simple_form_for User.new, url: user_registration_path do |f| %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

<div id='loginmodal' class='modal fade' role='dialog'>
  <div class='form-holder'>
    <h1>Login Form</h1>

    <%= simple_form_for(User.new, as: 'user', url: session_path('user')) do |f| %>
      <div class="form-inputs">
        <%= f.input :email, required: false, autofocus: true %>
        <%= f.input :password, required: false %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Log in" %>
      </div>
    <% end %>

  </div>
</div>

<script>
$(document).ready(function(){
  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substringRegex;
      // an array that will be populated with substring matches
      matches = [];
      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');
      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          matches.push(str);
        }
      });
      cb(matches);
    };
  };

  var titles = <%= @titles.to_json.html_safe %>

  $('#the-basics .typeahead').typeahead({
    hint: true,
    highlight: true,
    minLength: 1,
    selectable: 'Typeahead-selectable'
  },
  {
    name: 'titles',
    source: substringMatcher(titles)
  });
});
</script>

app/views/layouts/_subcrible.html.erb
<%= form_for(current_user.bookmarks.build, remote: true) do |f| %>
<%#= form_for(@bookmark, remote: true) do |f| %>
<%#= form_for(@bookmark, remote: true) do |f| %>
  <%= hidden_field_tag :manga_id, @manga.id %>
  <%= f.submit "Subcrible", class: 'btn btn-default' %>
<% end %>

app/views/layouts/_subcrible_form.html.erb
<% if user_signed_in? %>
  <div id='subcrible_form'>
    <% if current_user.follow?(@manga) %>
      <%= render 'layouts/unsubcrible' %>
    <% else %>
      <%= render 'layouts/subcrible' %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_top_and_new_mangas.html.erb
<ul class = 'top-mangas' %>
  <h1>Top Manga</h1>
  <% @top_mangas.each do |manga|%>
    <li>
      <%= image_tag manga.thumbnail, class:'top-thumbnail' %>
      <%= link_to manga.title, manga %>
    </li>
  <% end %>
</ul>

<ul class = 'new-mangas' %>
  <h1>New Manga</h1>
  <% @new_mangas.each do |manga|%>
    <li>
      <%= image_tag manga.thumbnail, class:'new-thumbnail' %>
      <%= link_to manga.title, manga %>
    </li>
  <% end %>
</ul>

app/views/layouts/_unsubcrible.html.erb
<%= form_for(current_user.bookmarks.find_by(manga_id: @manga.id), remote: true, html:{method: :delete}) do |f| %>
  <%= hidden_field_tag :manga_id, @manga.id %>
  <%= f.submit "Unsubcrible", class: 'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoang - Manga Reader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/mangas/_info.html.erb
<div class='manga-holder'>
  <div class='row info-box'>
    <div class='col-md-3 col-lg-3 col-xs-3 thumbnail'>
      <%= image_tag @manga.thumbnail %>
    </div>
    <div class='col-md-9 col-lg-9 col-xs-9 info'>
      <h1><%= @manga.title %></h1>
      <p><strong>Author: </strong>
        <% @manga.authors.each do |author| %>
          <span><%= link_to author, "/search?author=#{author}", method: 'post' %>, </span>
        <% end %>
      </p>
      <p><strong>Genre: </strong>
        <% @manga.genres.each do |genre| %>
          <span><%= link_to genre, "/search?genre=#{genre}", method: 'post' %>, </span>
        <% end %>
      </p>
      <p><strong>Status: </strong><%= @manga.status %></p>
      <p><strong>Description:</strong> <%= @manga.description %></p>

      <%= render 'layouts/subcrible_form' %>

    </div>
  </div>

  <div class="chapter-box">
    <% @chapters.each do |chapter| %>
      <div class='row'>
        <div class='col-md-9 col-lg-9 col-xs-9 chapter'>
          <%= link_to "#{chapter.chapter_number}", manga_chapter_path(@manga, chapter) %>
          <%#= chapter.chapter_index %>
        </div>
        <div class='col-md-3 col-lg-3 col-xs-3 time'>
          <span><%= chapter.date.to_date %></span>
        </div>
      </div>
    <% end %>
  </div>

</div>


<%= render 'layouts/comment' %>

app/views/mangas/_manga.html.erb
<div class='manga-box'>
  <%#= image_tag manga.thumbnail %>
  <%= link_to "#{manga.title}", manga, { 'data-toggle' => "tooltip",
                  :title => "<img src=" + manga.thumbnail + " style='width:200px; height: auto;' alt='Smiley'>
                              <h1>" + manga.title+ "</h1>
                              <p>" + manga.description + "</p>
                  ",
                  :class => "manga-path" } %>
  <% if !manga.status.nil? %>
    <% if manga.status == 'Completed' %>
      <span class='pull-right'><%= manga.status %></span>
    <% else %>
      <span class='pull-right'><%= link_to manga.chapters.first.chapter_number, manga_chapter_path(manga.id, manga.chapters.first.id) %></span>
      <% end %>
  <% end %>
  <br>
</div>

app/views/mangas/index.html.erb
<div class='main-page'>
  <div class='row'>
    <div class='col-lg-8 col-md-8 col-sm-8 col-xs-8' id='manga-list'>
      <div class='chap-feed' >
      	<div class='title'>
				<h3>Manga</h3>
				<h3 class='pull-right'>Status/Latest chapter</h3>
				</div>
			  <div class='manga-listing'>
			    <%= render @mangas %>
			    <%= will_paginate %>
  			</div>
      </div>
    </div>

    <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4' id='advance-search'>
    	<%= form_for :manga, url: search_path, method: 'get' do %>
	    	<h1>ADVANCE FILTERS</h1>
	    	<h2>Genres</h2>
	    	<ul class = 'genres row' %>
		    <% @genres.each do |genre| %>
		      <li class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
		      	<label class="btn triStateCheckBox btn-default">
							<input type="hidden" name=<%= genre.gsub(" ", "_") %> value="na"> <%= genre %> <span class="glyphicon"></span>
						</label>
		      </li>
		    <% end %>
		    </ul>
		    <h2>Status</h2>
        <div class="btn-group status-button" data-toggle="buttons">
  				<label class="btn btn-default active"><input type="radio" name="status" value=nil checked=""> All</label>
  				<label class="btn btn-default"><input type="radio" name="status" value="Ongoing"> Ongoing</label>
  				<label class="btn btn-default"><input type="radio" name="status" value="Completed"> Completed</label>
				</div>
        <br />
		    <button type="submit" class="btn btn-lg btn-default fiftyPercent" id='search-button'>
		    	<span class="glyphicon glyphicon-search margRight10 hidden-xs"></span>
		    	Submit
		    	<span class="hidden-xs"> Search</span>
		    </button>
		    <a href= '#' class="btn btn-lg btn-default fiftyPercent" id='clearform'>
		    	<span class="glyphicon glyphicon-fire margRight10 hidden-xs"></span>
		    	Clear
		    	<span class="hidden-xs"> Form</span>
		    </a>
		   <% end %>
    </div>
  </div>
</div>

app/views/mangas/show.html.erb
<div class='main-page'>
  <div class='row'>
    <div class='col-lg-8 col-md-8 col-sm-8 col-xs-8' id='manga-list'>
      <%= render 'info' %>
    </div>

    <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
      <%= render 'layouts/top_and_new_mangas' %>
    </div>
  </div>
</div>

app/views/pages/_feed.html.erb
<% @feeds_mangas.each do |manga| %>

  <%= link_to(manga) do %>

    <li class='col-md-3 col-lg-3 col-xs-3'>
      <div style="background-image: url(<%= manga.thumbnail %>);">
        <% chap = manga.chapters.min_by(&:chapter_index) %>
        <%= link_to chap.chapter_number, manga_chapter_path(manga, chap) %>
        <span class='pull-right'><%= time_ago_in_words(manga.updated_at) %></span>
      </div>
      <strong>
        <%= link_to manga.title, manga %>
      </strong>

      <br>

    </li>
  <% end %>
<% end %>

app/views/pages/_post_list.html.erb
<div id='infinite-scrolling'>
  <%=will_paginate(@feeds_mangas)%>
</div>

app/views/pages/home.html.erb
<div class='main-page'>
  <div class='row'>
    <div class='col-lg-8 col-md-8 col-sm-8 col-xs-8'>



      <div class="carousel-container">
        <br>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">


          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <% @cover_mangas.each_with_index do |manga, index| %>
              <div class='item'>
                <a href=<%= manga_path(manga.id) %> >
                  <%= image_tag manga.coverpic %>
                </a>
              </div>
            <% end %>
            <script type="text/javascript">
              $(document).ready(function(){
                $('.carousel-inner .item:first').addClass('active')
              });
            </script>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class='chap-feed' >
        <h1>Latest Chapters</h1>

        

        <ul id='manga-feed' class='row'>
          <%= render 'feed' %>
        </ul>
        <div id='infinite-scrolling'>
          <%= will_paginate @feeds_mangas %>  
        </div>
        

      </div>

    </div>

    <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
      <%= render 'layouts/top_and_new_mangas' %>
    </div>
  </div>
</div>

app/views/pages/home.js.erb
$('#manga-feed').append('<%= escape_javascript render('feed') %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@feeds_mangas) %>');